//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD
{
    using System;
    using System.Collections.Generic;
    
    public partial class s
    {
        public int id { get; set; }
        public int customer_id { get; set; }
        public double amount { get; set; }
        public System.DateTime date { get; set; }
        public string remark { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
